# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 22:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Use +254712345678 Format', max_length=128, unique=True)),
                ('idNumber', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)])),
                ('residence', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tbl_profile',
                'managed': True,
            },
        ),
    ]
