# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 01:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999999999)])),
                ('national_id', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)])),
                ('fully_clreared', models.BooleanField(default=False)),
                ('date_cleared', models.DateField(auto_now_add=True)),
                ('batch_numbers', models.IntegerField()),
                ('mpesa_trans_id', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_profiles',
                'managed': True,
            },
        ),
    ]
