# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 00:10
from __future__ import unicode_literals

import debts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[debts.models.validate_positive])),
                ('loan_balance', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[debts.models.validate_positive])),
                ('loan_issue_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Customer')),
            ],
            options={
                'db_table': 'tbl_due_listing',
                'managed': True,
            },
        ),
    ]
