# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 19:59
from __future__ import unicode_literals

import accounts.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('role', models.CharField(choices=[('RoleA', 'RoleA'), ('RoleB', 'RoleB')], default='RoleA', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'users',
                'db_table': 'tbl_users',
                'verbose_name': 'user',
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
    ]
