# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='clearing_mpesa_trans_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
